# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created: Wed Sep 30 17:42:43 2015
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(796, 578)
        self.centralWidget = QtWidgets.QWidget(Main)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(8)
        sizePolicy.setVerticalStretch(8)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(410, 450))
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.tableView = QtWidgets.QTableView(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(8)
        sizePolicy.setVerticalStretch(8)
        sizePolicy.setHeightForWidth(self.tableView.sizePolicy().hasHeightForWidth())
        self.tableView.setSizePolicy(sizePolicy)
        self.tableView.setMinimumSize(QtCore.QSize(390, 0))
        self.tableView.setObjectName("tableView")
        self.horizontalLayout_4.addWidget(self.tableView)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(8)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setMinimumSize(QtCore.QSize(390, 0))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.horizontalLayout_5.addWidget(self.tableWidget)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calendarWidget.sizePolicy().hasHeightForWidth())
        self.calendarWidget.setSizePolicy(sizePolicy)
        self.calendarWidget.setMinimumSize(QtCore.QSize(360, 0))
        self.calendarWidget.setMaximumSize(QtCore.QSize(500, 16777215))
        self.calendarWidget.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.NoVerticalHeader)
        self.calendarWidget.setObjectName("calendarWidget")
        self.verticalLayout.addWidget(self.calendarWidget)
        self.tabWidget_2 = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget_2.setMinimumSize(QtCore.QSize(360, 0))
        self.tabWidget_2.setMaximumSize(QtCore.QSize(500, 16777215))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.taskList = QtWidgets.QListWidget(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.taskList.setFont(font)
        self.taskList.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.taskList.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.taskList.setProperty("isWrapping", False)
        self.taskList.setObjectName("taskList")
        self.gridLayout_3.addWidget(self.taskList, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.columnView = QtWidgets.QColumnView(self.tab_4)
        self.columnView.setObjectName("columnView")
        self.gridLayout_2.addWidget(self.columnView, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_4, "")
        self.verticalLayout.addWidget(self.tabWidget_2)
        self.gridLayout.addLayout(self.verticalLayout, 0, 1, 1, 1)
        Main.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(Main)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 796, 25))
        self.menuBar.setObjectName("menuBar")
        self.menu_2 = QtWidgets.QMenu(self.menuBar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menuBar)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menuBar)
        self.menu_4.setObjectName("menu_4")
        self.menu_5 = QtWidgets.QMenu(self.menuBar)
        self.menu_5.setObjectName("menu_5")
        self.menu_6 = QtWidgets.QMenu(self.menuBar)
        self.menu_6.setObjectName("menu_6")
        Main.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(Main)
        self.statusBar.setObjectName("statusBar")
        Main.setStatusBar(self.statusBar)
        self.toolBar = QtWidgets.QToolBar(Main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBar.sizePolicy().hasHeightForWidth())
        self.toolBar.setSizePolicy(sizePolicy)
        self.toolBar.setMovable(False)
        self.toolBar.setIconSize(QtCore.QSize(90, 30))
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setFloatable(False)
        self.toolBar.setObjectName("toolBar")
        Main.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.task_add_menu = QtWidgets.QAction(Main)
        self.task_add_menu.setObjectName("task_add_menu")
        self.fast_task_add_menu = QtWidgets.QAction(Main)
        self.fast_task_add_menu.setObjectName("fast_task_add_menu")
        self.action_2 = QtWidgets.QAction(Main)
        self.action_2.setObjectName("action_2")
        self.action_4 = QtWidgets.QAction(Main)
        self.action_4.setObjectName("action_4")
        self.action_5 = QtWidgets.QAction(Main)
        self.action_5.setObjectName("action_5")
        self.action_6 = QtWidgets.QAction(Main)
        self.action_6.setObjectName("action_6")
        self.action_7 = QtWidgets.QAction(Main)
        self.action_7.setObjectName("action_7")
        self.action_8 = QtWidgets.QAction(Main)
        self.action_8.setObjectName("action_8")
        self.action_10 = QtWidgets.QAction(Main)
        self.action_10.setObjectName("action_10")
        self.action_11 = QtWidgets.QAction(Main)
        self.action_11.setObjectName("action_11")
        self.action_12 = QtWidgets.QAction(Main)
        self.action_12.setObjectName("action_12")
        self.action_14 = QtWidgets.QAction(Main)
        self.action_14.setObjectName("action_14")
        self.action_16 = QtWidgets.QAction(Main)
        self.action_16.setObjectName("action_16")
        self.action_17 = QtWidgets.QAction(Main)
        self.action_17.setObjectName("action_17")
        self.action_19 = QtWidgets.QAction(Main)
        self.action_19.setObjectName("action_19")
        self.action_20 = QtWidgets.QAction(Main)
        self.action_20.setObjectName("action_20")
        self.action_21 = QtWidgets.QAction(Main)
        self.action_21.setObjectName("action_21")
        self.action_22 = QtWidgets.QAction(Main)
        self.action_22.setObjectName("action_22")
        self.action_24 = QtWidgets.QAction(Main)
        self.action_24.setObjectName("action_24")
        self.task_add_bar = QtWidgets.QAction(Main)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/done2.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.task_add_bar.setIcon(icon)
        self.task_add_bar.setObjectName("task_add_bar")
        self.add_fast_task_bar = QtWidgets.QAction(Main)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/contract11.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_fast_task_bar.setIcon(icon1)
        self.add_fast_task_bar.setObjectName("add_fast_task_bar")
        self.tracker_bar = QtWidgets.QAction(Main)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/time36.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tracker_bar.setIcon(icon2)
        self.tracker_bar.setObjectName("tracker_bar")
        self.add_tracker_note_bar = QtWidgets.QAction(Main)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/deadlines.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_tracker_note_bar.setIcon(icon3)
        self.add_tracker_note_bar.setObjectName("add_tracker_note_bar")
        self.add_event_bar = QtWidgets.QAction(Main)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/agreement.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_event_bar.setIcon(icon4)
        self.add_event_bar.setIconVisibleInMenu(True)
        self.add_event_bar.setObjectName("add_event_bar")
        self.menu_2.addAction(self.action_6)
        self.menu_2.addAction(self.action_7)
        self.menu_2.addAction(self.action_8)
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.action_10)
        self.menu_3.addAction(self.task_add_menu)
        self.menu_3.addAction(self.fast_task_add_menu)
        self.menu_3.addAction(self.action_2)
        self.menu_3.addSeparator()
        self.menu_3.addAction(self.action_4)
        self.menu_3.addAction(self.action_5)
        self.menu_4.addAction(self.action_17)
        self.menu_4.addSeparator()
        self.menu_4.addAction(self.action_19)
        self.menu_4.addAction(self.action_20)
        self.menu_4.addAction(self.action_21)
        self.menu_4.addAction(self.action_22)
        self.menu_4.addSeparator()
        self.menu_4.addAction(self.action_24)
        self.menu_5.addAction(self.action_14)
        self.menu_5.addSeparator()
        self.menu_5.addAction(self.action_16)
        self.menu_6.addAction(self.action_11)
        self.menu_6.addSeparator()
        self.menu_6.addAction(self.action_12)
        self.menuBar.addAction(self.menu_3.menuAction())
        self.menuBar.addAction(self.menu_2.menuAction())
        self.menuBar.addAction(self.menu_6.menuAction())
        self.menuBar.addAction(self.menu_5.menuAction())
        self.menuBar.addAction(self.menu_4.menuAction())
        self.toolBar.addAction(self.task_add_bar)
        self.toolBar.addAction(self.add_fast_task_bar)
        self.toolBar.addAction(self.tracker_bar)
        self.toolBar.addAction(self.add_tracker_note_bar)
        self.toolBar.addAction(self.add_event_bar)

        self.retranslateUi(Main)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", "Time For You"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Main", "Расписание"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Main", "Трекер"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("Main", "GTD"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("Main", "Полный список задач"))
        self.menu_2.setTitle(_translate("Main", "Правка"))
        self.menu_3.setTitle(_translate("Main", "Задачи"))
        self.menu_4.setTitle(_translate("Main", "Помощь"))
        self.menu_5.setTitle(_translate("Main", "Группы"))
        self.menu_6.setTitle(_translate("Main", "Трекер"))
        self.toolBar.setWindowTitle(_translate("Main", "toolBar"))
        self.task_add_menu.setText(_translate("Main", "Добавить задачу"))
        self.fast_task_add_menu.setText(_translate("Main", "Быстрое создание задачи"))
        self.action_2.setText(_translate("Main", "Создать событие"))
        self.action_4.setText(_translate("Main", "Список задач"))
        self.action_5.setText(_translate("Main", "Выполненные задачи"))
        self.action_6.setText(_translate("Main", "Вырезать"))
        self.action_7.setText(_translate("Main", "Копировать"))
        self.action_8.setText(_translate("Main", "Вставить"))
        self.action_10.setText(_translate("Main", "Параметры"))
        self.action_11.setText(_translate("Main", "Создать запись"))
        self.action_12.setText(_translate("Main", "Посмотреть трекер"))
        self.action_14.setText(_translate("Main", "Создать группу"))
        self.action_16.setText(_translate("Main", "Список групп"))
        self.action_17.setText(_translate("Main", "Документация"))
        self.action_19.setText(_translate("Main", "Как создать задачу"))
        self.action_20.setText(_translate("Main", "Отличия быстрых задач"))
        self.action_21.setText(_translate("Main", "Трекер"))
        self.action_22.setText(_translate("Main", "События"))
        self.action_24.setText(_translate("Main", "О программе"))
        self.task_add_bar.setText(_translate("Main", "Добавить задачу"))
        self.add_fast_task_bar.setText(_translate("Main", "Быстрое создание задачи"))
        self.tracker_bar.setText(_translate("Main", "Трекер"))
        self.tracker_bar.setToolTip(_translate("Main", "Показать трекер"))
        self.add_tracker_note_bar.setText(_translate("Main", "Добавить в трекер"))
        self.add_tracker_note_bar.setToolTip(_translate("Main", "Добавить запись в трекер"))
        self.add_event_bar.setText(_translate("Main", "Добавить событие"))
        self.add_event_bar.setToolTip(_translate("Main", "Добавить событие"))

